package db

import models.Article
import models.countArticle
import models.listArticle

fun createDBArticle(){
    listArticle[countArticle]= Article(countArticle+1,"Post-mating gene expression of Mexican fruit fly females: disentangling the effects of the male accessory glands","L. Sirot, R. Bansal, C. J. Esquivel, M. Arteaga-Vázquez, M. Herrera-Cruz, V. A. C. Pavinato, S. Abraham, K. Medina-Jiménez, M. Reyes-Hernández, A. Dorantes-Acosta, D. Pérez-Staples (2021)","Biologic",12.25,10,false,0,"Journal of Comparative Physiology A",2021,"January")
    listArticle[countArticle]= Article(countArticle+1,"Role of arbuscular mycorrhizal symbiosis in remediation of anthropogenic soil pollution","Laura Yesenia Solís-Ramos, Cristofer Coto-López & Antonio Andrade-Torres (2021)","Medical",15.5,10,false,0,"Symbiosis",2019,"February")
    listArticle[countArticle]= Article(countArticle+1,"Extractos acuosos de plantas como inhibidores de la germinación de urediniosporas de Hemileia vastatrix; la roya anaranjada del café","José Antonio García-Pérez, Enrique Alarcón-Gutiérrez, Vianey del Rocio Torres Pelayo (2021)","Science",18.75,10,true,0,"Revista Alianzas y Tendencias BUAP (AyTBUAP)",2017,"March")
    listArticle[countArticle]= Article(countArticle+1,"Spatial relationships between spiders and their host vascular epiphytes within shade trees in a Mexican coffee plantation","Luis G. Quijano-Cuervo, Francisco Emmanuel Méndez-Castro, Dinesh Rao, Federico Escobar Sarria, Simoneta Negrete-Yankelevich ","Biologic",22.52,10,false,0,"bioTROPICA",2015,"April")
    listArticle[countArticle]= Article(countArticle+1,"Batch and Semi-Continuous Anaerobic Digestion of Industrial Solid Citrus Waste for the Production of Bioenergy","Erik Samuel Rosas-Mendoza, Andrea Alvarado-Vallejo, Norma Alejandra Vallejo-Cantú, Raúl Snell-Castro, Sergio Martínez-Hernández and Alejandro Alvarado-Lassman ","Medical",25.25,10,false,0,"Processes",2013,"May")
    listArticle[countArticle]= Article(countArticle+1,"Many paths, one destination: mapping the movements of a kleptoparasitic spider on the host’s web","Rosales-García, R., Tapia-McClung, H., Narendra, A., Dinesh Rao ","Science",28.5,10,false,0,"Journal of Comparative Physiology A",2011,"June")
    listArticle[countArticle]= Article(countArticle+1,"Combined Effects of Methoprene and Metformin on Reproduction, Longevity, and Stress Resistance in Anastrepha ludens (Diptera: Tephritidae): Implications for the Sterile Insect Technique","Eva Aceves-Aparicio, Diana Pérez-Staples, José Arredondo, Aleph Corona-Morales, Jorge Morales-Mávil, Francisco Díaz-Fleischer ","Biologic",31.75,10,true,0,"Journal of Economic Entomology",2009,"July")
    listArticle[countArticle]= Article(countArticle+1,"Changes in chemical and structural composition of sugarcane bagasse caused by alkaline pretreatments [Ca(OH)2 and NaOH] modify the amount of endoglucanase and ß-glucosidase produced by Aspergillus niger in solid-state fermentation","Enrique Alarcón, Christian Hernández, Gabriela García, Fabio Ziarelli, Beatriz Gutiérrez-Rivera, Ricardo Musule, Gerardo Vázquez-Marrufo & Terrence G. Gardner ","Medical",35.50,10,false,0,"Chemical Engineering Communications",2007,"August")
    listArticle[countArticle]= Article(countArticle+1,"Biological Activities of Different Strains of the Genus Ganoderma spp. (Agaricomycetes) from Mexico","Victoria Espinosa-García, Guillermo Mendoza, Alla V. Shnyreva, José M. Padrón, & Ángel Trigos ","Science",38.25,10,false,0,"International Journal of Medicinal Mushrooms",2005,"September")
    listArticle[countArticle]= Article(countArticle+1,"Patterns of Gonadic Development and Operational Sex Ratio Promote Promiscuity of Euxesta bilimeki (Diptera:Ulidiidae)","Christian L. Rodríguez-Enríquez, Diana Pérez-Staples, Oscar Rios-Cardenas and Juan Rull ","Biologic",41.5,10,true,0,"Annals of the Entomological Society of America",2003,"October")
    listArticle[countArticle]= Article(countArticle+1,"Vocalizaciones asociadas al comportamiento colonial de Cacicus chrysonotus leucoramphus (Icteridae) en Colombia","Guaitarilla, D. A., Ortiz-Pérez, J. P., Calderón-Leytón, J. J., Gómez-Martínez, M. A., Trujillo-Torres, C. M., & Fernández, R. A. ","Medical",44.75,10,false,0,"Biota Colombiana",2001,"November")
    listArticle[countArticle]= Article(countArticle+1,"Prey colour biases of araneophagic mud-daubing wasps","Luis E. Robledo-Ospina, Nathan Morehouse, Federico Escobar, Armando Falcón-Brindis, María Luisa Jiménez, Dinesh Rao ","Science",48.20,10,false,0,"Animal Behaviour",1999,"December")
    listArticle[countArticle]= Article(countArticle+1,"Fir forest demography using matrix projections: Anomaly precipitation due to climatic change decrease population viability","Lázaro R.Sánchez-Velásquez, María del Rosario Pineda-López, Sara P. Ibarra-Zavaleta, Yitsendi López-Serrano ","Biologic",51.25,10,false,0,"Lázaro R.Sánchez-Velásquez, María del Rosario Pineda-López, Sara P. Ibarra-Zavaleta, Yitsendi López-Serrano ",1997,"January")
    listArticle[countArticle]= Article(countArticle+1,"Genetic diversity in oak populations under intensive management for fuelwood in the Sierra de Zongolica, Mexico","Miguel Ángel Vega-Ortega, Jesús Llanderal-Mendoza, Patricia Gerez-Fernández, Citlalli López Binnqüist ","Medical",54.5,10,true,0,"Annals of Applied Biology",1995,"February")
    listArticle[countArticle]= Article(countArticle+1,"Physiological stabilization, community characterization, and nitrogen degradation dynamics in an anammox consortium from estuarine sediments","Jaime J. Ronzón Bravo, Flor de María Cuervo-López, Antonio Andrade Torres, Mario A. Arteaga-Vázquez, Sergio Martínez Hernández ","Science",57.75,10,false,0,"Water Environment Research",1993,"March")
    listArticle[countArticle]= Article(countArticle+1,"The role of seed size in the emergence and survival of seedlings in contrasting environments: the case of Ceiba aesculifolia","Ivonne Martínez-González, Lázaro Rafael Sánchez-Velázquez,, Betsabé Ruiz-Guerra, María del Rosario Pineda-López & Noé Velázquez-Rosas ","Biologic",61.99,10,false,0,"New Forests",1991,"April")
    listArticle[countArticle]= Article(countArticle+1,"Soil Chemical Properties and Biological Processes Under Pine Trees With and Without Dendroctonus Bark Beetle Infestation","F. Vázquez-Ochoa, F. Reverchon, L. R. Sánchez-Velásquez, C. Ruíz-Montiel & M. R. Pineda-López ","Medical",64.25,10,false,0,"Journal of Sustainable Forestry",1989,"May")
    listArticle[countArticle]= Article(countArticle+1,"Antiproliferative potential of 3ß,5a,6ß,7a-tetrahydroxyergosta-8(14),22-diene produced by Acremonium persicinum isolated from an alkaline crater lake in Puebla, Mexico","César Franceschy, César Espinoza, José M. Padrón, Gandhi Landa-Cadena, Manuel Nortec, José J. Fernández, Alla Shnyrevad and Ángel Trigos ","Science",67.5,10,true,0,"Natural Product Research",1987,"June")
}